name: Build & Release
on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            cmd: "./makemac.sh -sb -parser-xerces --validation-parser --pack --skip-samples"
            artifact: "makemsix-darwin-x64"
          - os: ubuntu-latest
            cmd: "./makelinux.sh -sb --validation-parser --pack --skip-samples"
            artifact: "makemsix-linux-x64"
          - os: windows-latest
            cmd: "./makewin.cmd x64 -sb -parser-xerces --validation-parser --pack --skip-samples -mt"
            artifact: "makemsix-win32-x64"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      - name: "Setup CMake"
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: "3.20.x"
      - name: "Run Build"
        run: ${{ matrix.cmd }}
      - name: "Run Tests"
        run: .vs/msixtest/msixtest
      - name: "Publish Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: .vs/bin/makemsix

